1. Считайте датасет из файла train.csv

In [17]:
#pip install numpy
#pip install pandas
import numpy as np
import pandas as pd

Data = pd.read_csv('train.csv')
Data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

2. Выведите основную информацию о датасете: информацию о типах данных, число пропусков, средние значения и т.д.

In [18]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [19]:
Data.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [20]:
Data.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

3. Посчитайте процент выживаемости у каждого класса пассажиров (Pclass)

In [23]:
Survived_by_class = Data.groupby('Pclass')['Survived'].sum()
Survived_by_class

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [24]:
All_by_class = Data['Pclass'].value_counts()
All_by_class

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [25]:
Survived_in_percent = (Survived_by_class / All_by_class) * 100
Survived_in_percent

Pclass
1    62.962963
2    47.282609
3    24.236253
dtype: float64

4. Выведите самое популярное мужское и самое популярное женское имя на корабле

In [95]:
def extract_first_name(full_name):
    parts = full_name.split(', ')
    if len(parts) > 1:
        name_part = parts[1]
        name = name_part.split(' ')[1] # убираем Mr, Mrs, Miss
        return name
    return None

Data['First_Name'] = Data['Name'].apply(extract_first_name)
Data[Data['Sex'] == 'male']['First_Name'].value_counts().head(1)

First_Name
William    35
Name: count, dtype: int64

In [96]:
Data[Data['Sex'] == 'female']['First_Name'].value_counts().head(1)

First_Name
William    13
Name: count, dtype: int64

5. Выведите самое популярное мужское и самое популярное женское имя на корабле в каждом классе

In [104]:
# Самое популярное мужское имя в 1 классе
Data[(Data['Sex'] == 'male') & (Data['Pclass'] == 1)]['First_Name'].value_counts().head(1)

First_Name
William    11
Name: count, dtype: int64

In [ ]:
# Самое популярное мужское имя во 2 классе
Data[(Data['Sex'] == 'male') & (Data['Pclass'] == 2)]['First_Name'].value_counts().head(1)

First_Name
William    9
Name: count, dtype: int64

In [ ]:
# Самое популярное мужское имя в 3 классе
Data[(Data['Sex'] == 'male') & (Data['Pclass'] == 3)]['First_Name'].value_counts().head(1)

First_Name
William    15
Name: count, dtype: int64

In [ ]:
# Самое популярное женское имя в 1 классе
Data[(Data['Sex'] == 'female') & (Data['Pclass'] == 1)]['First_Name'].value_counts().head(1)

First_Name
John    4
Name: count, dtype: int64

In [ ]:
# Самое популярное женское имя во 2 классе
Data[(Data['Sex'] == 'female') & (Data['Pclass'] == 2)]['First_Name'].value_counts().head(1)

First_Name
William    6
Name: count, dtype: int64

In [ ]:
# Самое популярное женское имя в 3 классе
Data[(Data['Sex'] == 'female') & (Data['Pclass'] == 3)]['First_Name'].value_counts().head(1)

First_Name
Anna    7
Name: count, dtype: int64

6. Выведите часть таблицы с пассажирами, возраст которых больше 44 лет

In [107]:
Data[Data['Age'] > 44]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First_Name
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S,Elizabeth
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S,(Mary
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.0,1,0,PC 17572,76.7292,D33,C,Henry
...,...,...,...,...,...,...,...,...,...,...,...,...,...
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,Peter
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S,Frederick
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S,Richard
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,Victor
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C,Thomas

7. Выведите часть таблицы с пассажирами, возраст которых меньше 44 лет и которые мужского пола

In [108]:
Data[(Data['Age'] > 44) & (Data['Sex'] == 'male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,First_Name
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S,Timothy
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S,Edward
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C,Engelhart
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.0,1,0,36973,83.4750,C83,S,Henry
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,Herbert
...,...,...,...,...,...,...,...,...,...,...,...,...,...
771,772,0,3,"Jensen, Mr. Niels Peder",male,48.0,0,0,350047,7.8542,NaN,S,Niels
789,790,0,1,"Guggenheim, Mr. Benjamin",male,46.0,0,0,PC 17593,79.2000,B82 B84,C,Benjamin
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S,Johan
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S,Peter
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S,Victor

8. Выведите количества n-местных кабин (в которых было 2, 3, 4, ... человека)

In [140]:
tt = Data['Cabin'].value_counts()
res = 0
for i in range(len(tt)):
    if tt.iloc[i] > 1:
        res +=1
res

46